version: 2.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: techlife/face_recognition
          tag: latest
      - docker/push:
          image: techlife/face_recognition
          tag: latest
