version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
      - auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: echo "hello world"
