# 参考
# https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

# Workflow名
name: Shell Commands
# イベントトリガー
# Git Pushした時にこのワークフローを実行する
on: [push]

jobs:
  # job名(任意の名前で良い)
  run-shell-commmand:
    # virtual machineの形式を指定
    runs-on: ubuntu-latest
    container: #起動するコンテナイメージを指定
      image: pinto0309/raspios_lite_armhf:2022-06-16_bullseye #指定のdockerイメージを使用
    # jobのステップ
    steps:
      # ステップ名
      # - name: echo a string
      #   run: echo "Hello World"
      # ステップ2
      - name: multiline script
        run: | # 複数のコマンドを記載したいときは|(パイプ)で繋ぐ
          node -v
          npm -v
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install build-essential \
              cmake \
              gfortran \
              git \
              wget \
              curl \
              graphicsmagick \
              libgraphicsmagick1-dev \
              libatlas-base-dev \
              libavcodec-dev \
              libavformat-dev \
              libboost-all-dev \
              libgtk2.0-dev \
              libjpeg-dev \
              liblapack-dev \
              libswscale-dev \
              pkg-config \
              python3-dev \
              python3-numpy \
              python3-pip \
              zip
          sudo apt-get clean